import { AppLanguage } from "@/constants/app-preferences";

type ScheduleOption = "now" | "in2h" | "tomorrow9";

const APP_COPY = {
  es: {
    panicButton: {
      permissionTitle: "Permiso de ubicación requerido",
      permissionMessage:
        "Activa la ubicación para enviar la alerta de emergencia con tu posición actual.",
      channelErrorTitle: "No se pudo abrir WhatsApp/SMS",
      channelErrorMessage:
        "No hay una app compatible para enviar la alerta en este dispositivo.",
      sendErrorTitle: "Error al enviar alerta",
      sendErrorMessage:
        "No se pudo obtener tu ubicación o abrir la app de mensajería.",
      confirmTitle: "Confirmar alerta de emergencia",
      confirmMessage: "¿Quieres enviar tu alerta con ubicación actual?",
      cancel: "Cancelar",
      sendAlert: "Enviar alerta",
      chooseTitle: "Elegir destinatario",
      chooseMessage:
        "No tienes un contacto confiable activo. Elige cómo enviar y selecciona el destinatario.",
      whatsappPick: "WhatsApp (elegir contacto)",
      smsPick: "SMS (elegir contacto)",
      sending: "ENVIANDO",
      panic: "PÁNICO",
      holdHint: "Mantén presionado en caso de emergencia",
      a11yLabel: "Botón de pánico",
      a11yHint: "Mantén presionado para enviar alerta con ubicación actual",
      emergencyBody: (lat: number, lon: number) =>
        `🚨 [RescueNow] ¡EMERGENCIA! Necesito asistencia técnica urgente. Mi ubicación es: https://maps.google.com/?q=${lat},${lon}`,
    },
    categories: {
      mech: "Mecánico",
      tow: "Grúa",
      lock: "Cerrajero",
      plumb: "Plomero",
    },
    modal: {
      alert: "ALERTA CRÍTICA",
      title: "Emergencia rápida",
      subtitle: "Selecciona tu tipo de incidente para priorizar la asistencia.",
      routeStatus: "Unidad disponible para salida inmediata",
      close: "Cerrar",
      options: [
        {
          id: "1",
          title: "Mecánico urgente",
          subtitle: "Falla severa en carretera",
          icon: "construct" as const,
        },
        {
          id: "2",
          title: "Grúa inmediata",
          subtitle: "Traslado en emergencia",
          icon: "car-sport" as const,
        },
        {
          id: "3",
          title: "Plomería crítica",
          subtitle: "Fuga o rotura mayor",
          icon: "water" as const,
        },
      ],
    },
    auth: {
      login: {
        sectionTitle: "Ingresa a tu cuenta",
        sectionSubtitle:
          "Selecciona tu perfil y accede rápido a la asistencia.",
        userTitle: "Entrar como Usuario",
        userDesc: "Solicita asistencia técnica o vial en tiempo real.",
        technicianTitle: "Entrar como Técnico",
        technicianDesc: "Recibe solicitudes cercanas y brinda apoyo inmediato.",
        email: "Correo electrónico",
        emailPlaceholder: "ejemplo@correo.com",
        password: "Contraseña",
        passwordPlaceholder: "Tu contraseña",
        forgot: "Olvidé mi contraseña",
        submit: "Continuar",
        footer: "En RescueNow priorizamos la seguridad y respuesta rápida.",
        register: "¿No tienes cuenta? Regístrate",
      },
      register: {
        sectionTitle: "Crear cuenta",
        sectionSubtitle:
          "Registra tu perfil para solicitar o brindar asistencia.",
        userTitle: "Registro como Usuario",
        userDesc: "Podrás solicitar ayuda en carretera o domicilio.",
        technicianTitle: "Registro como Técnico",
        technicianDesc: "Recibirás servicios cercanos según tu ubicación.",
        fullName: "Nombre completo",
        fullNamePlaceholder: "Tu nombre",
        phone: "Teléfono",
        phonePlaceholder: "Ej. 4431234567",
        email: "Correo electrónico",
        emailPlaceholder: "ejemplo@correo.com",
        password: "Contraseña",
        passwordPlaceholder: "Mínimo 6 caracteres",
        confirmPassword: "Confirmar contraseña",
        confirmPasswordPlaceholder: "Repite tu contraseña",
        passwordMismatch: "Las contraseñas no coinciden.",
        submit: "Crear cuenta",
        loginLink: "¿Ya tienes cuenta? Inicia sesión",
      },
      forgotPassword: {
        sectionTitle: "Recuperar contraseña",
        sectionSubtitle:
          "Ingresa tu correo y te enviaremos instrucciones para restablecer tu acceso.",
        email: "Correo electrónico",
        emailPlaceholder: "ejemplo@correo.com",
        sentMessage:
          "Te enviamos un enlace de recuperación. Revisa tu bandeja de entrada.",
        sendLink: "Enviar enlace",
        backToLogin: "Volver a iniciar sesión",
      },
    },
    navigation: {
      homeTab: "Inicio",
      optionsTab: "Ajustes",
      emergencyModal: "Emergencia",
    },
    tabs: {
      options: {
        topLabel: "Cuenta demo",
        title: "Opciones",
        loading: "Cargando preferencias...",
        profileName: "Miembro Rescue",
        activeBadge: "Activo",
        languageTitle: "Idioma de la app",
        languageSubtitle: "Elige el idioma para mensajes y alertas",
        spanish: "Español",
        english: "Inglés",
        emergencyContactTitle: "Contacto confiable",
        emergencyContactSubtitle:
          "Puedes guardar un número para enviar la alerta directo sin elegir destinatario cada vez.",
        trustedInputLabel: "Número de contacto",
        trustedInputPlaceholder: "Ejemplo: +525512345678",
        directSwitchLabel: "Enviar directo al contacto confiable",
        saveContact: "Guardar contacto",
        clearContact: "Quitar contacto",
        saving: "Guardando...",
        logout: "Cerrar sesión",
        userOptions: [
          {
            id: "premium",
            title: "Comprar premium",
            subtitle: "Prioridad de asistencia y beneficios exclusivos",
            icon: "diamond-outline" as const,
            accent: "accent" as const,
          },
          {
            id: "payment",
            title: "Métodos de pago",
            subtitle: "Administrar tarjetas y facturación",
            icon: "card-outline" as const,
            accent: "primary" as const,
          },
          {
            id: "support",
            title: "Soporte y ayuda",
            subtitle: "Centro de ayuda y contacto rápido",
            icon: "help-circle-outline" as const,
            accent: "primary" as const,
          },
        ],
      },
      home: {
        tagline: "Asistencia técnica y vial en tiempo real",
        locating: "Ubicando...",
        locationError: "No se pudo obtener tu ubicación en este momento.",
        locationPermissionError:
          "Activa ubicación para mostrar el mapa en tiempo real.",
        requestService: "Solicitar servicio",
        requestServiceSub: "Opciones normales de asistencia",
        tracking: "Seguimiento en vivo",
        trackingSub: "Visualiza avance y tiempo estimado",
        panicCounter: (count: number) =>
          `Activaciones de pánico (sesión): ${count}`,
        nearbyTitle: "Técnicos cercanos",
        etaPrefix: "ETA",
      },
      services: {
        step: "Paso 1 de 3",
        title: "¿Qué servicio necesitas?",
        activeAssistance: "Asistencia activa en tu zona",
        issueLabel: "Describe tu problema (opcional)",
        issuePlaceholder: "Ejemplo: Se me poncho una llanta en carretera.",
        categories: "Categorías disponibles",
        techAvailable: "Técnicos disponibles ahora",
        options: {
          mech: {
            title: "Mecánico",
            subtitle: "Fallas generales, batería o llantas",
          },
          tow: {
            title: "Grúa",
            subtitle: "Traslado de vehículo a taller",
          },
          lock: {
            title: "Cerrajero",
            subtitle: "Apertura de auto o domicilio",
          },
          plumb: {
            title: "Plomero",
            subtitle: "Fuga de agua o tubería",
          },
        },
      },
      tracking: {
        topTitle: "Espejo de ruta",
        title: "Tu técnico se acerca",
        etaLabel: "ETA",
        etaValue: "8 min",
        distance: "Distancia actual: 1.4 km",
        live: "Seguimiento en vivo",
        section: "Estado del servicio",
        service: "Servicio: RN-1024",
        status: "Estado: En progreso",
        diagnosis: "Diagnóstico: 75%",
        steps: [
          { id: "1", label: "Solicitud recibida", done: true, time: "12:01" },
          { id: "2", label: "Técnico asignado", done: true, time: "12:03" },
          { id: "3", label: "Técnico en camino", done: true, time: "12:05" },
          { id: "4", label: "Llegada estimada", done: false, time: "12:13" },
        ],
      },
      technicians: {
        step: "Paso 2 de 3",
        availableSuffix: "disponibles",
        categoryPlural: {
          mech: "Mecánicos",
          tow: "Grúas",
          lock: "Cerrajeros",
          plumb: "Plomeros",
        },
        activeNearby: (count: number) =>
          `${count} técnicos activos cerca de ti`,
        requestedWork: "Trabajo solicitado:",
        etaPrefix: "ETA",
        min: "min",
        completedServices: (jobs: number) => `${jobs} servicios completados`,
        available: "Disponible",
      },
      technicianDetail: {
        step: "Paso 3 de 3",
        title: "Detalle del técnico",
        etaSummary: (eta: number) => `Llegada estimada en ${eta} minutos`,
        rating: "Calificación",
        etaPrefix: "ETA",
        min: "min",
        services: "servicios",
        workLabel: "¿Qué trabajo necesitas?",
        workPlaceholder:
          "Ejemplo: Cambio de llanta trasera y revisión de presión.",
        mode: "Modalidad",
        normal: "Normal",
        urgent: "Urgente",
        complexity: "Complejidad",
        basic: "Básica",
        medium: "Media",
        high: "Alta",
        schedule: "Horario de servicio",
        now: "Ahora",
        in2h: "En 2 horas",
        tomorrow: "Mañana 9:00",
        suggestedPrices: "Precios sugeridos (aprox.)",
        base: "Base",
        recommendedEstimate: "Estimado recomendado",
        factors: "Factores aplicados",
        scheduleFactor: "Horario",
        distanceFactor: "Distancia",
        urgencyFactor: "Urgencia",
        complexityFactor: "Complejidad",
        nightSurcharge: "Recargo nocturno activo",
        weekendSurcharge: "Recargo fin de semana activo",
        confirm: "Confirmar y ver ruta",
      },
    },
  },
  en: {
    panicButton: {
      permissionTitle: "Location permission required",
      permissionMessage:
        "Enable location to send the emergency alert with your current position.",
      channelErrorTitle: "Could not open WhatsApp/SMS",
      channelErrorMessage:
        "No compatible messaging app was found on this device.",
      sendErrorTitle: "Failed to send alert",
      sendErrorMessage:
        "Could not get your location or open the messaging app.",
      confirmTitle: "Confirm emergency alert",
      confirmMessage: "Do you want to send your alert with current location?",
      cancel: "Cancel",
      sendAlert: "Send alert",
      chooseTitle: "Choose recipient",
      chooseMessage:
        "You do not have an active trusted contact. Choose a channel and pick the recipient.",
      whatsappPick: "WhatsApp (choose contact)",
      smsPick: "SMS (choose contact)",
      sending: "SENDING",
      panic: "PANIC",
      holdHint: "Press and hold in case of emergency",
      a11yLabel: "Panic button",
      a11yHint: "Press and hold to send an alert with your current location",
      emergencyBody: (lat: number, lon: number) =>
        `🚨 [RescueNow] EMERGENCY! I need urgent roadside or technical assistance. My location is: https://maps.google.com/?q=${lat},${lon}`,
    },
    categories: {
      mech: "Mechanic",
      tow: "Tow truck",
      lock: "Locksmith",
      plumb: "Plumber",
    },
    modal: {
      alert: "CRITICAL ALERT",
      title: "Quick emergency",
      subtitle: "Select your incident type to prioritize assistance.",
      routeStatus: "Unit available for immediate dispatch",
      close: "Close",
      options: [
        {
          id: "1",
          title: "Urgent mechanic",
          subtitle: "Severe roadside failure",
          icon: "construct" as const,
        },
        {
          id: "2",
          title: "Immediate tow truck",
          subtitle: "Emergency transport",
          icon: "car-sport" as const,
        },
        {
          id: "3",
          title: "Critical plumbing",
          subtitle: "Major leak or pipe burst",
          icon: "water" as const,
        },
      ],
    },
    auth: {
      login: {
        sectionTitle: "Sign in to your account",
        sectionSubtitle: "Select your profile and quickly access assistance.",
        userTitle: "Continue as User",
        userDesc: "Request technical or roadside assistance in real time.",
        technicianTitle: "Continue as Technician",
        technicianDesc:
          "Receive nearby requests and provide immediate support.",
        email: "Email address",
        emailPlaceholder: "example@email.com",
        password: "Password",
        passwordPlaceholder: "Your password",
        forgot: "Forgot my password",
        submit: "Continue",
        footer: "At RescueNow, safety and fast response come first.",
        register: "No account yet? Sign up",
      },
      register: {
        sectionTitle: "Create account",
        sectionSubtitle:
          "Register your profile to request or provide assistance.",
        userTitle: "Register as User",
        userDesc: "You will be able to request roadside or home assistance.",
        technicianTitle: "Register as Technician",
        technicianDesc:
          "You will receive nearby services based on your location.",
        fullName: "Full name",
        fullNamePlaceholder: "Your name",
        phone: "Phone number",
        phonePlaceholder: "Ex. 4431234567",
        email: "Email address",
        emailPlaceholder: "example@email.com",
        password: "Password",
        passwordPlaceholder: "Minimum 6 characters",
        confirmPassword: "Confirm password",
        confirmPasswordPlaceholder: "Repeat your password",
        passwordMismatch: "Passwords do not match.",
        submit: "Create account",
        loginLink: "Already have an account? Sign in",
      },
      forgotPassword: {
        sectionTitle: "Recover password",
        sectionSubtitle:
          "Enter your email and we will send instructions to reset your access.",
        email: "Email address",
        emailPlaceholder: "example@email.com",
        sentMessage: "We sent you a recovery link. Check your inbox.",
        sendLink: "Send link",
        backToLogin: "Back to sign in",
      },
    },
    navigation: {
      homeTab: "Home",
      optionsTab: "Settings",
      emergencyModal: "Emergency",
    },
    tabs: {
      options: {
        topLabel: "Demo account",
        title: "Options",
        loading: "Loading preferences...",
        profileName: "Rescue member",
        activeBadge: "Active",
        languageTitle: "App language",
        languageSubtitle: "Choose the language for alerts and messages",
        spanish: "Spanish",
        english: "English",
        emergencyContactTitle: "Trusted contact",
        emergencyContactSubtitle:
          "Save a phone number to send direct emergency alerts without choosing a recipient each time.",
        trustedInputLabel: "Contact phone",
        trustedInputPlaceholder: "Example: +525512345678",
        directSwitchLabel: "Send alert directly to trusted contact",
        saveContact: "Save contact",
        clearContact: "Remove contact",
        saving: "Saving...",
        logout: "Sign out",
        userOptions: [
          {
            id: "premium",
            title: "Get premium",
            subtitle: "Priority assistance and exclusive benefits",
            icon: "diamond-outline" as const,
            accent: "accent" as const,
          },
          {
            id: "payment",
            title: "Payment methods",
            subtitle: "Manage cards and billing",
            icon: "card-outline" as const,
            accent: "primary" as const,
          },
          {
            id: "support",
            title: "Support and help",
            subtitle: "Help center and quick contact",
            icon: "help-circle-outline" as const,
            accent: "primary" as const,
          },
        ],
      },
      home: {
        tagline: "Real-time technical and roadside assistance",
        locating: "Locating...",
        locationError: "Could not get your location right now.",
        locationPermissionError:
          "Enable location to show the live map in real time.",
        requestService: "Request service",
        requestServiceSub: "Standard assistance options",
        tracking: "Live tracking",
        trackingSub: "View progress and estimated arrival",
        panicCounter: (count: number) =>
          `Panic activations (session): ${count}`,
        nearbyTitle: "Nearby technicians",
        etaPrefix: "ETA",
      },
      services: {
        step: "Step 1 of 3",
        title: "What service do you need?",
        activeAssistance: "Active assistance in your area",
        issueLabel: "Describe your issue (optional)",
        issuePlaceholder: "Example: I got a flat tire on the highway.",
        categories: "Available categories",
        techAvailable: "Technicians available now",
        options: {
          mech: {
            title: "Mechanic",
            subtitle: "General faults, battery, or tires",
          },
          tow: {
            title: "Tow truck",
            subtitle: "Vehicle transport to a workshop",
          },
          lock: {
            title: "Locksmith",
            subtitle: "Car or home lock opening",
          },
          plumb: {
            title: "Plumber",
            subtitle: "Water leak or pipe issue",
          },
        },
      },
      tracking: {
        topTitle: "Route mirror",
        title: "Your technician is getting closer",
        etaLabel: "ETA",
        etaValue: "8 min",
        distance: "Current distance: 1.4 km",
        live: "Live tracking",
        section: "Service status",
        service: "Service: RN-1024",
        status: "Status: In progress",
        diagnosis: "Diagnosis: 75%",
        steps: [
          { id: "1", label: "Request received", done: true, time: "12:01" },
          { id: "2", label: "Technician assigned", done: true, time: "12:03" },
          {
            id: "3",
            label: "Technician on the way",
            done: true,
            time: "12:05",
          },
          { id: "4", label: "Estimated arrival", done: false, time: "12:13" },
        ],
      },
      technicians: {
        step: "Step 2 of 3",
        availableSuffix: "available",
        categoryPlural: {
          mech: "Mechanics",
          tow: "Tow trucks",
          lock: "Locksmiths",
          plumb: "Plumbers",
        },
        activeNearby: (count: number) => `${count} active technicians near you`,
        etaPrefix: "ETA",
        min: "min",
        requestedWork: "Requested work:",
        completedServices: (jobs: number) => `${jobs} completed services`,
        available: "Available",
      },
      technicianDetail: {
        step: "Step 3 of 3",
        title: "Technician details",
        etaSummary: (eta: number) => `Estimated arrival in ${eta} minutes`,
        rating: "Rating",
        etaPrefix: "ETA",
        min: "min",
        services: "services",
        workLabel: "What work do you need?",
        workPlaceholder: "Example: Rear tire replacement and pressure check.",
        mode: "Mode",
        normal: "Standard",
        urgent: "Urgent",
        complexity: "Complexity",
        basic: "Basic",
        medium: "Medium",
        high: "High",
        schedule: "Service schedule",
        now: "Now",
        in2h: "In 2 hours",
        tomorrow: "Tomorrow 9:00",
        suggestedPrices: "Suggested prices (approx.)",
        base: "Base",
        recommendedEstimate: "Recommended estimate",
        factors: "Applied factors",
        scheduleFactor: "Schedule",
        distanceFactor: "Distance",
        urgencyFactor: "Urgency",
        complexityFactor: "Complexity",
        nightSurcharge: "Night surcharge active",
        weekendSurcharge: "Weekend surcharge active",
        confirm: "Confirm and view route",
      },
    },
  },
} as const;

export function getAppCopy(language: AppLanguage) {
  return APP_COPY[language];
}

export function getScheduleLabel(
  language: AppLanguage,
  schedule: ScheduleOption,
  hourLabel: string,
): string {
  if (schedule === "now") {
    return language === "en" ? "Now" : "Ahora";
  }

  if (schedule === "in2h") {
    return language === "en" ? "In 2 hours" : "En 2 horas";
  }

  return language === "en" ? `Tomorrow, ${hourLabel}` : `Mañana, ${hourLabel}`;
}
