export const FUN_FACTS_FREE: string[] = [
  // --- DATOS MÉDICOS Y SUPERVIVENCIA ---
  "💡 **Dato curioso:** En México, el 70% de los accidentes viales ocurren por distracciones al volante. ¡Mantén el teléfono abajo! 📱🚫",
  "🌡️ **Tip del día:** Revisa la presión de tus llantas al menos una vez al mes. Llantas con baja presión aumentan el consumo de gasolina hasta un 10%.",
  "⛽ **¿Sabías que...** Cargar gasolina temprano en la mañana te da un poco más de combustible? El frío hace que la gasolina sea más densa. 🌅",
  "🔋 **Tip de mantenimiento:** La vida útil promedio de una batería de auto es de 3 a 5 años. Si tu carro tarda en encender, podría ser hora de cambiarla.",
  "🚗 **Dato curioso:** Mantener tu tanque por encima del 25% ayuda a preservar la bomba de gasolina y evita que sedimentos lleguen al motor.",
  "🛞 **Tip de seguridad:** Los neumáticos deben rotarse cada 10,000 km para un desgaste uniforme. Revisa la profundidad del dibujo con una moneda.",
  "🏥 **¿Sabías que...** Tener tu ficha médica actualizada en RescueNow puede salvar tu vida. Los paramédicos la ven al llegar. ¡Actualízala! 🆘",
  "🌧️ **Tip para lluvia:** Reduce tu velocidad un 30% en lluvia. Los frenos necesitan el doble de distancia para detenerte en pavimento mojado.",
  "🔧 **Dato curioso:** El aceite de motor se debe cambiar cada 5,000-7,500 km. Un motor sin aceite se puede dañar en solo 30 minutos de uso.",
  "📞 **¿Sabías que...** En México puedes llamar al 911 incluso sin saldo en tu celular. La llamada es gratuita desde cualquier teléfono. 🆓",
  "🚦 **Tip de seguridad:** Mantén siempre 3 segundos de distancia con el auto de enfrente. En carretera, aumenta a 5 segundos.",
  "⚡ **Dato curioso:** Un foco fundido en tu auto puede costarte una multa de hasta $1,300 MXN. Revisa tus luces cada semana. 💡",
  "🧊 **Tip de invierno:** Si tu parabrisas se empaña, enciende el aire acondicionado frío por 30 segundos. Seca el aire más rápido que la calefacción.",
  "🔑 **¿Sabías que...** Dejar el auto encendido con las puertas cerradas puede activar el bloqueo automático. ¡Siempre lleva una copia de tu llave!",
  "🏍️ **Tip para motociclistas:** Siempre usa guantes y casco certificado. El 80% de las lesiones fatales en moto son por trauma craneal.",
  "🦺 **Tip de seguridad:** Llevar un chaleco reflejante en la guantera es obligatorio en muchas carreteras del mundo y altamente recomendado en México.",
  "🧼 **¿Sabías que...** La suciedad en el parabrisas aumenta dramáticamente el brillo cegador de las luces de otros autos en la noche? Mantenlo limpio.",
  "🧯 **Prevención:** Un extintor pequeño tipo PQS en tu cajuela puede evitar que una falla eléctrica menor destruya todo tu auto.",
  "🐕 **Dato curioso:** Frenar bruscamente a 50 km/h hace que un perro sin cinturón de seguridad salga proyectado con el peso de una vaca pequeña.",
  "🛣️ **Tip de carretera:** Si manejas de noche, usa las líneas laterales blancas para guiarte en lugar de mirar directamente las luces de los autos contrarios.",
  "🎒 **Tip de emergencia:** Siempre lleva un botiquín de primeros auxilios. Las vendas y gasas caducan con el tiempo, ¡revísalas anualmente!",
  "🚦 **¿Sabías que...** El color rojo de los semáforos se eligió porque tiene la longitud de onda más larga y se dispersa menos con la niebla?",
  "🥵 **Tip de calor:** Si el auto estuvo bajo el sol, baja las cuatro ventanillas y abre y cierra una puerta rápidamente 5 veces para sacar el calor.",
  "🔊 **Mecánica:** Si escuchas un chillido al frenar, es la pequeña pestaña metálica de la balata avisándote que es momento de reemplazarla.",
  "💧 **Tip vital:** Nunca uses agua de la llave para el radiador a largo plazo. Sus minerales oxidan el motor por dentro. Usa solo anticongelante.",
  "🌬️ **Aerodinámica:** Manejar a 120 km/h con las ventanas abajo gasta más gasolina por resistencia al aire que ir a 120 km/h con el aire acondicionado puesto.",
  "🛑 **Seguridad vial:** De noche en zonas oscuras sin semáforo, destellar tus luces altas avisa a otros de tu presencia en los cruces.",
  "⏱️ **Concentración:** Escribir un mensaje en el celular te quita los ojos del camino 5 segundos. A 90 km/h, viajas la longitud de una cancha de fútbol a ciegas.",
  "🚭 **Conducción:** Fumar adentro de tu auto impregna irreversibles los plásticos del tablero, devaluando el precio de reventa de tu coche.",
  "🚙 **Ángeles Verdes:** ¿Te quedaste botado en carretera en México? Marca al 078. Los Ángeles Verdes acuden gratis a ayudarte.",
  "🪛 **Tip rápido:** Si los bornes de tu batería están blancos y oxidados, puedes limpiarlos virtiéndoles agua mineral o refresco de cola temporalmente.",
  "🔦 **¿Sabías que...** Siempre debes traer una linterna en la guantera. El flash del celular drena la batería y tu principal salvavidas en emergencias es el teléfono.",
  "🛣️ **Niebla:** En zonas de niebla, NUNCA enciendas las luces altas. El agua en el aire actuará como espejo y te cegará a ti mismo.",
  "🥵 **Sobrecalentamiento:** Si tu auto se calienta de repente, encender la calefacción al máximo puede extraer el aire caliente del motor y salvarlo temporalmente.",
  "🛞 **Desgaste:** Si las llantas se desgastan más de los lados que del centro, están desinfladas. Si se desgastan del centro, están sobreinfladas.",
  "⚠️ **Tip de choque:** En un golpe laminero, NUNCA ofrezcas disculpas ni asumas la culpa de inmediato con la otra persona. Espera al ajustador de tu seguro.",
  "📋 **Aseguradoras:** Siempre debes traer el nombre de tu seguro y tu número de póliza visible en la guantera o guardado en RescueNow.",
  "🚘 **Punto Ciego:** Ajusta tus espejos laterales de forma que apenas dejes de ver la orilla de tu propio auto. Reducirás el punto ciego enormemente.",
  "💤 **Microsueños:** Bajar la ventana o poner música alta NO evita que te quedes dormido al volante. Tomar café y dormir 15 minutos en una gasolinera sí.",
  "🌊 **Lluvia:** Si tu auto empieza a patinar en un charco (Aquaplaning), no frenes de golpe. Suelta el acelerador suavemente y sujeta firme el volante.",
  "🌡️ **Calefacción:** El sistema de calefacción calienta el aire usando el calor del motor de tu carro, por eso no gasta tanta gasolina extra.",
  "📱 **GPS:** Colocar tu celular sobre el volante mientras manejas no solo distrae: si la bolsa de aire explota, el celular te golpeará la cara a 300 km/h.",
  "💡 **Direccionales:** Usar direccionales no gasta gasolina ni te cobra impuestos. ¡Úsalas, salvan decenas de vidas diariamente!",
  "🔑 **Dato:** En autos más viejitos, apagar el carro al bajar pendientes empinadas apaga tu dirección hidráulica y tus frenos. ¡Nunca lo hagas!",
  "🚗 **Curiosidad:** El olor a 'auto nuevo' es en realidad desgasificación de solventes plásticos, gomas y pegamentos frescos.",
  "🔧 **Líquidos:** Un tapón de gasolina suelto puede encender la temida luz 'Check Engine', ya que el sistema detecta fuga en la presión de vapores.",
  "🧽 **Tip estético:** Frotar pasta de dientes blanca común en faros amarillentos y opacos te devolverá más de un 60% de iluminación nocturna en emergencias.",
  
  // --- CHISTES AUTOMOTRICES (BÁSICOS) FREES ---
  "🤣 **Humor:** ¿Qué le dice un semáforo al otro? —'¡No me mires, que me estoy cambiando!' 🚦",
  "🤣 **Humor:** ¿Cuál es el carro favorito de los perros? —¡El 'Guau'-di! 🐶🚘",
  "🤣 **Humor:** Un policía me detuvo y dijo 'Papeles'. Le dije 'Tijeras, ¡yo gano!' y me fui volando... (No lo intentes) 🚔",
  "🤣 **Humor:** ¿Qué hace una vaca manejando un carro? —¡Muuuu-danzas! 🐄🚛",
  "🤣 **Humor:** ¿Por qué los carros viejos no van al gimnasio? —¡Porque ya tienen la banda de transmisión rota! 💪🚗",
  "🤣 **Humor:** ¿En qué se parece un auto bomba a un sándwich? —¡En que los dos explotan cuando menos te lo esperas! 🥪💥",
  "🤣 **Humor:** Mi mecánico me dijo que la reparación costaba $10,000 pesos. Lo abracé. Él lloró. Yo lloré. Y el auto sigue sin prender. 😭",
  "🤣 **Humor:** Papá, ¿puedo usar el coche? —'No sin mi supervisión'. —'¡Pero si no tengo súper-visión, solo uso lentes normales!' 👓",
  "🤣 **Humor:** ¿Qué le dijo una llanta ponchada al rin? —'Me siento desinflada, esto ya no rueda igual entre nosotros.' 🛞💔",
  "🤣 **Humor:** Dicen que el amor es ciego... Hasta que intentas estacionarte en reversa y rayas el auto de tu suegro. 🫣🚗",
  "🤣 **Humor:** ¿Qué coche usa el mismísimo Darth Vader? —¡Un Nissan 'Skywalker'! 🌌🚙",
  "🤣 **Humor:** ¿Por qué los semáforos nunca sonríen? —Porque tienen el trabajo más estresante: detener chismes de tráfico todo el día. 🚥",
  "🤣 **Humor:** Iba en un taxi y me dice el chofer: '¿Le importa si pongo música?'. Le dije: 'Para nada, ¿toca algún instrumento?'. Me bajó ahí mismo. 🚕",
  "🤣 **Humor:** Un coche en venta: 'Viendo detalles de pintura'. Vas a verlo y le falta el motor entero. 'Ah, es que el motor pintaba para funcionar y no funcionó'. 🥸",
  "🤣 **Humor:** Amor, se descompuso mi carro. —'¿Qué tiene?'. —'El mecánico dijo que una pieza pequeñita entre el asiento y el volante'. —'¡Ese eres tú, idiota!' 👤",
  "🤣 **Humor:** ¿Cómo maldice un mecánico enojado? —¡Vete al Mofle! 😠🔧",
  "🤣 **Humor:** ¿Cómo sabes si a un fantasma le gustan los autos? —Porque siempre manejan Buuuu-gattis. 👻🏎️",
  "🤣 **Humor:** 'Señor oficial, yo no estaba tomando, mi carro funciona con etanol y yo le di respiración de boca a boca'. 🍻🚔",
  "🤣 **Humor:** Juez, juro que mi GPS me dijo 'gira a la derecha'. Que justo ahí hubiera un lago ya no es mi problema náutico. 🚤🗺️",
  "🤣 **Humor:** 'Mecánico, mi auto hace un ruido clack-clack muy raro'. El mecánico saca un martillo, lo golpea y dice: 'Listo, ahora hace bang-bang'. 🛠️",
  "🤣 **Humor:** Me compré un auto tan viejo que su GPS todavía te dice que puedes tomar un carruaje si el tráfico en reforma está apretado. 🐎📍",
  "🤣 **Humor:** Manejar en el tráfico pesado te enseña dos cosas de la humanidad: que el tiempo es relativo, y que todos mienten en sus direccionales. 🚦",
  "🤣 **Humor:** Amor, ¿tú crees en el amor a primera vista? —'Solo si el tablero no marca Check Engine al prender'. 💸"
];

export const FUN_FACTS_PREMIUM: string[] = [
  // --- DATOS AVANZADOS VIP ---
  "🌟 **Premium:** Si tu auto tiene turbo, NUNCA lo apagues de golpe tras un viaje en carretera. Déjalo encendido 1-2 minutos para que el aceite refrigere la turbina.",
  "🛑 **Legal VIP:** En caso de accidente con heridos, NINGUNA autoridad de tránsito te puede obligar por ley a declarar en el lugar de los hechos. Puedes esperar a tu abogado.",
  "🌟 **Premium:** Los autos automáticos NO deben cambiarse nunca a neutral ('N') en las bajadas para 'ahorrar'. Es un mito y arruina tus balatas drásticamente.",
  "🧾 **Seguros VIP:** Revisa si tu Póliza tiene 'Deducible 0% en Terceros sin Seguro'. Significa que si alguien sin seguro te choca y huye, tu pago será Cero absoluto.",
  "🌟 **Premium:** El octanaje (Premium 92 vs Magna 87) indica la resistencia a explotar antes de tiempo, no te da 'más potencia'. Si tu manual pide 87, la Premium es tirar dinero.",
  "🧲 **Premium ABS:** Así funciona tu ABS: Mide el giro de cada rueda 20 veces por segundo. Si detecta bloqueo, suelta pinza milisegundos para permitirte maniobrar.",
  "📸 **Legal VIP:** En un choque, lo primero que debes fotografiar son las LLANTAS de todos los vehículos (hacia dónde apuntan) y los escombros tirados en el piso.",
  "🌟 **Premium:** Una transmisión automática muerta cuesta fortunas. El aceite ATF pierde viscosidad a los 80,000 km y lamentablemente casi nadie lo cambia a tiempo.",
  "👮 **Legal VIP:** En un retén aleatorio, un oficial NO puede revisar tu cajuela sin una orden, a menos que un perro marcara droga o detecte una actividad ilícita obvia.",
  "🌟 **Premium Mecánica:** ¿RPM suben y bajan solas en rojo? 80% de las veces es provocado por minúsculas fugas de vacío en las mangueras. Una reparación barata.",
  "💡 **Legal VIP:** Si tu llanta explota por caer en un bache gigante estatal, el gobierno está obligado legalmente a pagarte el daño a través de una demanda de Responsabilidad Patrimonial.",
  "🌟 **Premium:** El foco 'Check Engine' fijo suele ser problema de emisiones. Pero si la luz *parpadea intermitentemente*, apaga el carro YA. Significa que tu pistón falló y dañará todo.",
  "⛽ **Premium:** Evita cargar gasolina cuando veas a la Pipa descargando. La turbulencia revuelve lodos sucios del fondo del tanque gigantesco que irán directo a tus inyectores.",
  "🌟 **Premium:** Nunca gires el volante en 'seco' a tope manteniendo presión. Es la forma más fácil de calentar y reventar la bomba hidráulica de tu dirección.",
  "📋 **Aseguradora Pro:** Usar llantas lisas o de otro tamaño al original le da argumento técnico a tu seguro civil para invalidar un choque, llamándolo 'negligencia'.",
  "🌟 **Premium OBD2:** Al borrar códigos del tablero antes de vender un auto, los monitores internos de emisiones OBD2 marcan 'INCOMPLETOS'. Un escáner delata los engaños rápido.",
  "🛑 **Frenos Premium:** Para frenar desde 200 km/h a cero en pistas pesadas se usa cerámica o carbono. En ciudad, los discos perforados se agrietan más fácil que los normales lisos.",
  "🌟 **Resguardo VIP:** Tratar psicológicamente a niños tras un impacto frontal exige evitar hablarles del suceso de golpe. Aísla su vista rápida y ofréceles algo familiar (mochila).",
  "⚖️ **Legal VIP:** Firmar 'No responsabilidad médica' a favor del ajustador del conductor que te chocó por error anula tu derecho a reclamar daño en las cervicales horas después.",
  "🚗 **Premium AWD:** Un sistema 'Tracción en las Cuatro Ruedas Permanente' exige cambiar SIEMPRE las 4 llantas al mismo tiempo. Poner solo 2 puede destruir el eje Diferencial Central.",
  "🏁 **Turbo VIP:** El retraso al pisar el acelerador (Lag) no es defecto humano: los autos electrónicos nuevos lo introducen por computadora intencionalmente para la curva de torque.",
  "🔧 **Suspensión Pro:** Cuando cambies amortiguadores, exige frenos de base de poliuretano. Dejarlos crudos y rotos reduce la vida a la mitad para los nuevos amortiguadores.",
  "🌟 **Sensor O2 VIP:** Echar aditivos dudosos a granel destruirá en semanas el polvo de iridio y circonio interno de tus catalizadores. Cada sensor estropeado afectará enormemente tus MPGs.",
  "👮 **Tránsito VIP:** Un agente estatal no tiene facultades ejecutivas en tramos netamente 'Federales' sin que haya acompañamiento de Guardia Nacional, ni pueden levantar grúas arbitrarias.",
  "📉 **Depreciación VIP:** El valor comercial indemnizable de tu auto baja CADA MES del libro de depreciación. Un accidente en Diciembre paga hasta 10% menos valor que uno ocurrido en Enero.",
  "🌟 **Evolución ECU VIP:** Si prestas el auto 1 semana a tu primo lento y al usarlo lo sientes burdo, es normal. La ECU automotriz moderna adaptó la inyección a la 'pisada' tranquila.",
  "💧 **Cuidado Motor VIP:** Lavar todo el bloque del motor directo con lanzas de agua a alta presión en los autolavados inundará sin falta tus módulos y alternador, oxidándolos por dentro.",
  "🔒 **Clonación RFID:** Los hackers roban llaves 'Keyless' copiando la señal inactiva con antenas parabólicas desde el exterior a 10 metros de tu bolsa. Solución: Cajas de plomo tipo Faraday a menos de $150.",
  "🛑 **Bolsas VIP:** ¡Jamás subas los pies al tablero de copiloto! Una bolsa de aire pasajera estalla a 350 km/h en cuestión de centésimas. Conducir a un choque destruiría articulaciones.",
  "⚖️ **Defensa VIP:** Un croquis dibujado por ti sin aval de un Perito o de tu ajustador particular NO es una confesión inapelable en un choque controversial, la biomecánica vehicular domina el peritaje.",

  // --- CHISTES AUTOMOTRICES IRONÍAS EXCLUSIVAS (VIP) ---
  "💎 **Humor VIP:** Un abogado choca su BMW brutalmente. Grita escandalizado: '¡Mi auto, mi hermoso BMW, está destrozado!'. El paramédico le contesta: 'Compañero... ¡no ve que la lámina le arrancó el brazo izquierdo!'. El abogado se mira el hombro sangrando y grita desconsolado: '¡Por la virgen santísima, MI RELOJ ROLEX!' 😂🍾",
  "💎 **Humor Técnico Premium:** Dicen que el dinero no compra la felicidad perfecta, pero es preferible llorar estacionado en un Porshe 911 a 310 por hora con los frenos Brembo oliendo a fibra abrasiva que en un vocho. 🏎️🤣",
  "💎 **Humor VIP:** Un sujeto lleva su coche Mercedes Benz a la distribuidora oficial porque parpadea una luz. El mecánico enchufa una computadora por 2 segundos y dice: 'Fueron 5 mil pesos, el termómetro ambiental de afuera estaba marcando en Fahrenheit y era letal a la vista'. 💸💡",
  "💎 **Humor Premium:** 'Le juro ajustador, yo no tuve la culpa... Es que el árbol brincó de repente al camellón y yo iba tranquilamente texteando en reversa'. (Textos 100% reales de casos de colisiones a terceros). 🌲🚗",
  "💎 **Humor Multa VIP:** Señor juez de tránsito, le aseguro que no me pasé ese putrefacto semáforo intencionalmente. Mi auto venía a tanta velocidad que por la relatividad cuántica, la onda expansiva roja de Doppler se tornó azul ante mis retinas. 🔴🔵🚦",
  "💎 **Humor Ajustadores VIP:** Cuenta la ciencia que solo hay un evento medible que se ha comprobado ser infinitamente más lento que retroceder en Viaducto en quincena: Un agente de seguro solicitándole autorización por WhatsApp al centro matriz un viernes a las 18:00 pm. 🐢📑",
  "💎 **Humor Tuning Premium:** En realidad sí quiero apoyar el sueño tuning tipo Fast and Furious de todos los chicos, hasta que veo que el recibo de rectificación de bancada del bloque motor que volaron a nivel orbital se fue a 400 mil pesos por culpa del óxido nitroso virtual. 🏎️💥",
  "💎 **Acertijo VIP:** ¿Cuál es la forma más rápida y probada de convertir un ligero silbido aerodinámico romántico proveniente del quemacocos trasero, en un problema catastrófico de ruidos guturales rechinantes y muy pesados y caros? —Subiéndole el estéreo M/Karman con el bajo de graves retumbando al 100%. 🔊🔩",
  "💎 **Humor Taller Pro:** Un cliente llega al taller Porsche 'Mi auto huele raro dentro cuando acelero'. Mecánico de bata blanca entra, mira bajo la llanta y concluye dictamen clínico premium de grado europeo: 'Señor, usted acaba de atropellar un mapache en estado avanzado de putrefacción que está soldado a su convertidor catalítico hirviendo'. 🦝🔬",
  "💎 **Humor Financiero Rápido:** Inviertes ochenta mil benditos pesos en unos rines forjados asimétricos hermosos fabricados en las mismas forjas de Thor, y misteriosamente, de la madrugada a la mañana, todos los baches y rejillas traicioneras de avenida periférico parecen tener las dimensiones perfectas para tu desgracia. 🕳️🔪"
];
